runtime: nodejs
env: flexible
threadsafe: true
env_variables:
  INSTANCE_CONNECTION_NAME: 'esp-mobile-182605:us-central1:esp'
  SQL_DATABASE: postgres
  SQL_PASSWORD: seniordesign
  SQL_USER: postgres
beta_settings:
  cloud_sql_instances: 'esp-mobile-182605:us-central1:esp'